[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600

build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Wno-unused-parameter

check_tool = clangtidy
check_flags =
    clangtidy: --config-file=.clang-tidy
